CREATE TABLE category (
    ids INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (ids)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE subject (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    categoryId INT(11) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (categoryId)
        REFERENCES category(ids)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE topic (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    subjectId INT(11) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (subjectId)
        REFERENCES subject(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE question (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    topicId INT(11) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (topicId)
        REFERENCES topic(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
